export type SelectType =
    | 'lamp'
    | 'rgbLamp'
    | 'colorMode'
    | 'colorTemp'
    | 'dimmer'
    | 'hue'
    | 'saturation'
    | 'sensor'
    | 'button0'
    | 'button1'
    | 'button2'
    | 'button3'
    | 'doorbell'
    | 'presenceSensor'
    | 'smokeAlarm'
    | 'awayButton';
